
services:
  database:
    container_name: cycle_database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database

volumes:
  database_volume:
    name: database_volume