
services:
  database:
    container_name: cycle_database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - cycle_network
    volumes:
      - database_volume:/var/lib/postgresql
  api:
    container_name: cycle_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - cycle_network

volumes:
  database_volume:
    name: cycle_database_volume

networks:
  cycle_network:
    name: cycle_network